/*SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA='up' and TABLE_NAME like '%context%'
*/

SELECT DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME like '%SpLocaleContainerItem%ID%'
AND TABLE_SCHEMA='specify';